#include "common.hpp"
#include "tinyECS/components.hpp"

const Tile TOP_LEFT_WALL_CORNER2 = Tile{
    TEXTURE_ASSET_ID::TOP_LEFT_WALL_CORNER2,
    TEXTURE_ASSET_ID::TOP_LEFT_WALL_CORNER2_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile TOP_RIGHT_WALL_CORNER2 = Tile{
    TEXTURE_ASSET_ID::TOP_RIGHT_WALL_CORNER2,
    TEXTURE_ASSET_ID::TOP_RIGHT_WALL_CORNER2_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile BOTTOM_LEFT_WALL_CORNER2 = Tile{
    TEXTURE_ASSET_ID::BOTTOM_LEFT_WALL_CORNER2,
    TEXTURE_ASSET_ID::BOTTOM_LEFT_WALL_CORNER2_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile BOTTOM_RIGHT_WALL_CORNER2 = Tile{
    TEXTURE_ASSET_ID::BOTTOM_RIGHT_WALL_CORNER2,
    TEXTURE_ASSET_ID::BOTTOM_RIGHT_WALL_CORNER2_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile TOP_LEFT_WALL_CORNER1 = Tile{
    TEXTURE_ASSET_ID::TOP_LEFT_WALL_CORNER1,
    TEXTURE_ASSET_ID::TOP_LEFT_WALL_CORNER_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile TOP_RIGHT_WALL_CORNER1 = Tile{
    TEXTURE_ASSET_ID::TOP_RIGHT_WALL_CORNER1,
    TEXTURE_ASSET_ID::TOP_RIGHT_WALL_CORNER_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile BOTTOM_LEFT_WALL_CORNER1 = Tile{
    TEXTURE_ASSET_ID::BOTTOM_LEFT_WALL_CORNER1,
    TEXTURE_ASSET_ID::BOTTOM_LEFT_WALL_CORNER_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile BOTTOM_RIGHT_WALL_CORNER1 = Tile{
    TEXTURE_ASSET_ID::BOTTOM_RIGHT_WALL_CORNER1,
    TEXTURE_ASSET_ID::BOTTOM_RIGHT_WALL_CORNER_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile TOP_LEFT_WALL1 = Tile{
    TEXTURE_ASSET_ID::TOP_LEFT_WALL1,
    TEXTURE_ASSET_ID::TOP_LEFT_WALL1_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile TOP_RIGHT_WALL1 = Tile{
    TEXTURE_ASSET_ID::TOP_RIGHT_WALL1,
    TEXTURE_ASSET_ID::TOP_RIGHT_WALL1_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile BOTTOM_LEFT_WALL1 = Tile{
    TEXTURE_ASSET_ID::BOTTOM_LEFT_WALL1,
    TEXTURE_ASSET_ID::BOTTOM_LEFT_WALL1_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile BOTTOM_RIGHT_WALL1 = Tile{
    TEXTURE_ASSET_ID::BOTTOM_RIGHT_WALL1,
    TEXTURE_ASSET_ID::BOTTOM_RIGHT_WALL1_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile BOTTOM_WALL1 = Tile{
    TEXTURE_ASSET_ID::BOTTOM_WALL1,
    TEXTURE_ASSET_ID::BOTTOM_WALL1_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile TOP_WALL1 = Tile{
    TEXTURE_ASSET_ID::TOP_WALL1,
    TEXTURE_ASSET_ID::TOP_WALL1_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile RIGHT_WALL1 = Tile{
    TEXTURE_ASSET_ID::RIGHT_WALL1,
    TEXTURE_ASSET_ID::RIGHT_WALL1_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile LEFT_WALL1 = Tile{
    TEXTURE_ASSET_ID::LEFT_WALL1,
    TEXTURE_ASSET_ID::LEFT_WALL1_NORMAL,
    TILE_ID::WALL,
    {1, 1}
};

const Tile FLOOR_TILE_1 = Tile{
    TEXTURE_ASSET_ID::FLOOR_1,
    TEXTURE_ASSET_ID::FLOOR_1_NORMAL,
    TILE_ID::FLOOR,
    {1, 1}
};

const Tile FLOOR_TILE_2 = Tile{
    TEXTURE_ASSET_ID::FLOOR_2,
    TEXTURE_ASSET_ID::FLOOR_2_NORMAL,
    TILE_ID::FLOOR,
    {1, 1}
};

const Tile FLOOR_TILE_5 = Tile{
    TEXTURE_ASSET_ID::FLOOR_5,
    TEXTURE_ASSET_ID::DEFAULT_NORMAL,
    TILE_ID::FLOOR,
    {1, 1}
};

const std::array<Tile, 3> FLOOR_TILES = {
    FLOOR_TILE_1,
    FLOOR_TILE_2,
    FLOOR_TILE_5
};

const std::unordered_map<int, Tile> BASE_TILES_ID_MAP = {
	{17, FLOOR_TILE_5},
	{20, FLOOR_TILE_5},
	{33, TOP_LEFT_WALL1},
	{34, TOP_WALL1},
	{35, TOP_RIGHT_WALL1},
	{36, TOP_LEFT_WALL_CORNER1},
	{37, TOP_RIGHT_WALL_CORNER1},
	{44, LEFT_WALL1},
	{46, RIGHT_WALL1},
	{47, BOTTOM_LEFT_WALL_CORNER1},
	{48, BOTTOM_RIGHT_WALL_CORNER1},
	{55, BOTTOM_LEFT_WALL1},
	{56, BOTTOM_WALL1},
	{57, BOTTOM_RIGHT_WALL1},
	{66, FLOOR_TILE_1},
	{69, FLOOR_TILE_5},
	{77, FLOOR_TILE_2},
	{69, FLOOR_TILE_5}
};
